### ISSUE TITLE
Clean AccessDB

### ISSUE THREAD

**Issue by paul-gilbertson** [jncc/marine-habitat-classification#1]

**Comment by meganevparry** [comment]
There are copies of tables and old tables which aren’t needed – WEB_ddBIOTOPE, WEB_SLIDES-backup, WEB_BIOT_RELATION pre 6 May 2016, WEB_BIOT_SPECIES pre 26 feb 2016, WEB_BIOTOPE pre 26 feb 2016

WEB_BIOT_SPECIES
I’m not sure what the FAITH column is for. temp1_STRENGTH and temp2_SED_ABUND appear to be empty and I’m not sure what they are for. 

WEB_BIOTOPE
All fields required 

WEB_BIOTOPE_HIERARCHY
This will be used to create the hierarchy – I expect this information is required in some format. 

WEB_ddBIOTOPE
I’m not sure what this table is for

WEB_OLD_CODE
This information is required. 

WEB_SLIDES
This information is required. 
The orientation isn’t necessarily needed, but was presumably used on for the old website.

**Comment by paul-gilbertson** [comment]
Is there a clean copy somewhere?

**Comment by meganevparry** [comment]
WEB_SLIDES - not sure why these are assigned an NBNKey as an identifier, I would have thought it would be better to have BIOTOPE_KEY

**Comment by meganevparry** [comment]
I've saved a cleaned version (marbiotope-deepsea_MPcleaned.mdb) here: Z:\Prog110-FutureData\Marine\Data\Marine Habitat Classifications

I've deleted out the tables where the information was explicitly necessary, but I presume there was a reason they were included originally. They must have been used to create the old web pages.

**Comment by paul-gilbertson** [comment]
Perfect, closing issue.

**Comment by ulric-wilson** [comment]
Table WEB_ddlBIOTOPE provided the source for the Drop Down List (ddl) used on the Biotope Search page.
