### ISSUE TITLE
Add cookie consent/ssl/google analytics/footer links

### ISSUE THREAD

**Issue by mattdebont** [jncc/marine-habitat-classification#65]

**Comment by felixMasonJncc** [comment]
- [ ] Add privacy notice link in footer
 - [ ] Make header and footer content consistent with other sites
 - [ ] Cookie control and cross site cookie integration
 - [ ] Enable SSL

**Comment by CathyJinJNCC** [comment]
Currently referring to below links

http://jncc.gov.uk/about
http://jncc.gov.uk/terms-and-conditions
http://jncc.gov.uk/privacy
http://jncc.gov.uk/contact
http://jncc.gov.uk/cookies

**Comment by CathyJinJNCC** [comment]
Splitting header/footer consistency out into a separate ticket
