### ISSUE TITLE
Investigate and implement data roll back for MHC microsite 

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/marine-habitat-classification#67]
New biotopes/data not yet approved. Need to revert the new microsite back to agreed data ready for launch of the new JNCC website.

- [x] check data structure
- [ ] check its possible to deploy microsite without the fields and tables that are missing in the old structure (functionality intact?)

**Comment by LynnHeeley** [comment]
Old structure (in terms of fields and tables) has the following differences to the new structure: Tables missing: SpeciesCopy, WebHabitatCorrelation, WebPhoto (no data in this table in new structure - empty fields). 
Fields missing: 
- Web_Biot_Species table does not have:  relative_frequency field (rest same)
- Web_Biotope table does not have: sensitivity, derived from or faunal group
- Web_Old_Code table does not have previous fullname, relationship type, modification
No additional fields in old structure that are not present in new structure
A case of suppressing certain fields and certain tables in the app and translating the old data into the new data structure?

**Comment by CathyJinJNCC** [comment]
I believe SpeciesCopy is a duplicate/backup (taken of Web_Biot_Species while changes were being made to it) and can be safely ignored

**Comment by mattdebont** [comment]
Dependent on making changes in the database to support this

**Comment by CathyJinJNCC** [comment]
Done
