### ISSUE TITLE
Add google tag manager to mhc.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/marine-habitat-classification#83]
See attached code to add

[https://app.zenhub.com/files/109007369/8b307ea7-05cc-452b-9cbf-4cf392b2ff02/download](https://app.zenhub.com/files/109007369/8b307ea7-05cc-452b-9cbf-4cf392b2ff02/download)

**Comment by felixMasonJncc** [comment]
Tag manager implemented in site in all deployments. This should all now work as expected in google analytics.
