### ISSUE TITLE
Resolve 404 errors on mhc.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/marine-habitat-classification#85]
these pages below have links on them which result in a 404

https://mhc.jncc.gov.uk/	   https://mhc.jncc.gov.uk/media/1013/correlationdatabase201801.zip
https://mhc.jncc.gov.uk/resources/	https://mhc.jncc.gov.uk/media/1013/correlationdatabase201801.zip

**Comment by CathyJinJNCC** [comment]
Rescanned and looks clear now
