### ISSUE TITLE
Implement a robots.txt file on mhc.jncc.gov.uk/

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/marine-habitat-classification#87]
see similar page on
https://hub.jncc.gov.uk/robots.txt
but edit the list to be appropriate for this site

**Comment by jonparsonsjncc** [comment]
Also implement a sitemap.xml

**Comment by CathyJinJNCC** [comment]
http://internal-beta:9000/robots.txt

**Comment by jonparsonsjncc** [comment]
Hi @CathyJinJNCC happy for you to deploy to live
