### ISSUE TITLE
Create 404 page for mhc.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/marine-habitat-classification#90]
Use this page as a template for the body text
http://pre-live.jncc.gov.uk/404

**Comment by jonparsonsjncc** [comment]
Hi @CathyJinJNCC see wording to add below

Sorry, we've not been able to find the page or file you requested.

If you entered a web address, please check it was correct. You can also visit our home page, browse from the navigation above or use the search to find the information you need.

For more up to date information please visit the JNCC website home page - or feel free to contact us.

URLS
https://mhc.jncc.gov.uk/
https://jncc.gov.uk/
https://jncc.gov.uk/contact/?ref=mhc404

**Comment by CathyJinJNCC** [comment]
See https://mhc.jncc.gov.uk/boo
