### ISSUE TITLE
Create a 500 error page mhc.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/marine-habitat-classification#91]
please use this as an example

https://hub.jncc.gov.uk/fail

and set /fail as a url that will replicate it

please liaise with @PeteMontgomery who set this up on the hub

**Comment by jonparsonsjncc** [comment]
Hi @CathyJinJNCC the google tag manager code needs to be added - same tag manager code that is in the current site

text needs to be changed to:

Sorry we were unable to complete your request but our technical staff have been notified of the issue and will work to resolve it. If the problem persists please feel free to contact us.

Note: contact us needs to be a link to /contact/?ref=mhc500

Question: also could you confirm how the technical staff are going to be notified of this error

**Comment by CathyJinJNCC** [comment]
See https://mhc.jncc.gov.uk/biotopes/jnccmncr0
